<template>
	<auto-backstage :models="models"></auto-backstage>
</template>

<script>
	export default{
		name:'auto-backstage-view',
		data:()=>{
			return {
				getModelsByBG:false,
				models:{
					name:'商城后台管理系统',
					url:'http://192.168.43.84:8201',
					loginUrl:'/mall-auth/oauth/token',
					loginModel:{
						username:'admin',
						password:'macro123',
						grant_type:'password',
						client_id:'admin-app',
						client_secret:'123456'
					},
					childModels:[{
						name:'用户管理',
						url:'/mall-admin',
						childModel:[{
							name:'管理员',
							url:'/admin',
							queryUrl:'/list',
							queryMethod:'GET',
							deleteUrl:'/delete',
							deleteUrlAppend:true,
							deleteMethod:'POST',
							insertUrl:'/register',
							insertMethod:'POST',
							updateUrl:'/update',
							updateUrlAppend:true,
							updateMethod:'POST',
							queryModel:{
								keyword:null,
								pageSize:null,
								pageNum:null
							},
							insertModel:{
								username:null,
								password:null,
								icon:null,
								email:null,
								nickName:null,
								note:null
							}
						},{
							name:'会员等级',
							url:'/memberLevel',
							queryUrl:'/list',
							queryMethod:'GET',
							queryModel:{
								defaultStatus:''
							}
						},{
							name:'后台菜单管理',
							url:'/menu',
							queryUrl:'/treeList',
							queryMethod:'GET',
							insertUrl:'/create',
							insertMethod:'POST',
							updateUrl:'/update',
							updateMethod:'POSt',
							updateUrlAppend:true,
							deleteUrl:'/delete',
							deleteUrlAppend:true,
							deleteMethod:'POST',
						},{
							name:'资源分类管理',
							url:'/resourceCategory',
							queryUrl:'/listAll',
							queryMethod:'GET',
							insertUrl:'/create',
							insertMethod:'POST',
							updateUrl:'/update',
							updateMethod:'POSt',
							updateUrlAppend:true,
							deleteUrl:'/delete',
							deleteUrlAppend:true,
							deleteMethod:'POST',
						},{
							name:'后台资源管理',
							url:'/resource',
							queryUrl:'/listAll',
							queryMethod:'GET',
							insertUrl:'/create',
							insertMethod:'POST',
							updateUrl:'/update',
							updateMethod:'POSt',
							updateUrlAppend:true,
							deleteUrl:'/delete',
							deleteUrlAppend:true,
							deleteMethod:'POST'
						},{
							name:'后台用户角色管理',
							url:'/role',
							queryUrl:'/listAll',
							queryMethod:'GET',
							insertUrl:'/create',
							insertMethod:'POST',
							updateUrl:'/update',
							updateMethod:'POSt',
							updateUrlAppend:true,
							deleteUrl:'/delete',
							deleteUrlAppend:true,
							deleteMethod:'POST'
						}],
					},{
						name:'商品管理',
						url:'/mall-admin',
						childModel:[{
							name:'商品属性类别',
							url:'/productAttribute/category',
							queryUrl:'/list',
							queryMethod:'GET',
							insertUrl:'/create',
							insertMethod:'POST',
							deleteUrl:'/delete',
							deleteMethod:'POST',
							deleteUrlAppend:true,
							updateUrl:'/update',
							updateMethod:'POST',
							updateUrlAppend:true
						},{
							name:'商品属性',
							url:'/productAttribute',
							insertUrl:'/create',
							insertMethod:'POST',
							deleteUrl:'/delete',
							deleteMethod:'POST',
							deleteUrlAppend:true,
							updateUrl:'/update',
							updateMethod:'POST',
							updateUrlAppend:true,
							queryUrl:'/list',
							queryMethod:'GET',
							queryUrlAppend:'id',
							queryModel:{
								id:null,
								type:0,
								pageSize:5,
								pageNum:1
							}
						},{
							name:'商品分类',
							url:'/productCategory',
							insertUrl:'/create',
							insertMethod:'POST',
							deleteUrl:'/delete',
							deleteMethod:'POST',
							deleteUrlAppend:true,
							updateUrl:'/update',
							updateMethod:'POST',
							updateUrlAppend:true,
							queryUrl:'/list',
							queryMethod:'GET',
							queryUrlAppend:'parentId',
							queryModel:{
								parentId:null,
								pageSize:5,
								pageNum:1
							}

						},{
							name:'商品管理',
							url:'/product',
							insertUrl:'/create',
							insertMethod:'POST',
							deleteUrl:'/delete',
							deleteMethod:'POST',
							deleteUrlAppend:true,
							updateUrl:'/update',
							updateMethod:'POST',
							updateUrlAppend:true,
							queryUrl:'/list',
							queryMethod:'GET',
							queryModel:{
								pageSize:5,
								pageNum:1
							}
						},{
							name:'库存管理',
							url:'/sku',
							queryUrl:'',
							queryMethod:'GET',
							queryUrlAppend:'pid',
							queryModel:{
								pid:null,
								keyword:null
							}
						},{
							name:'品牌',
							url:'/brand',
							queryUrl:'/listAll',
							queryMethod:'GET',
							deleteUrl:'/delete',
							deleteMethod:'DELETE',
							insertUrl:'/insert',
							insertMethod:'PUT',
							updateUrl:'/update',
							updateMethod:'POST'
						}],
					},{
						name:'营销管理',
						url:'/mall-admin',
						childModel:[{
							name:'首页轮播管理',
							url:'/home/advertise',
							insertUrl:'/create',
							insertMethod:'POST',
							deleteUrl:'/delete',
							deleteMethod:'POST',
							deleteUrlAppend:true,
							updateUrl:'/update',
							updateMethod:'POST',
							updateUrlAppend:true,
							queryUrl:'/list',
							queryMethod:'GET',
							queryModel:{
								name:null,
								type:null,
								endTime:null,
								pageSize:5,
								pageNum:1
							}
						},{
							name:'首页品牌管理',
							url:'/home/brand',
							insertUrl:'/create',
							insertMethod:'POST',
							deleteUrl:'/delete',
							deleteMethod:'POST',
							deleteUrlAppend:true,
							updateUrl:'/update',
							updateMethod:'POST',
							updateUrlAppend:true,
							queryUrl:'/list',
							queryMethod:'GET',
							queryModel:{
								brandName:null,
								recommendStatus:null,
								pageSize:5,
								pageNum:1
							}
						},{
							name:'首页上新管理',
							url:'/home/newProduct',
							insertUrl:'/create',
							insertMethod:'POST',
							deleteUrl:'/delete',
							deleteMethod:'POST',
							deleteUrlAppend:true,
							updateUrl:'/update',
							updateMethod:'POST',
							updateUrlAppend:true,
							queryUrl:'/list',
							queryMethod:'GET',
							queryModel:{
								brandName:null,
								recommendStatus:null,
								pageSize:5,
								pageNum:1
							}
						},{
							name:'首页人气推荐管理',
							url:'/home/recommendProduct',
							insertUrl:'/create',
							insertMethod:'POST',
							deleteUrl:'/delete',
							deleteMethod:'POST',
							deleteUrlAppend:true,
							updateUrl:'/update',
							updateMethod:'POST',
							updateUrlAppend:true,
							queryUrl:'/list',
							queryMethod:'GET',
							queryModel:{
								brandName:null,
								recommendStatus:null,
								pageSize:5,
								pageNum:1
							}
						},{
							name:'首页专题推荐管理',
							url:'/home/recommendSubject',
							insertUrl:'/create',
							insertMethod:'POST',
							deleteUrl:'/delete',
							deleteMethod:'POST',
							deleteUrlAppend:true,
							updateUrl:'/update',
							updateMethod:'POST',
							updateUrlAppend:true,
							queryUrl:'/list',
							queryMethod:'GET',
							queryModel:{
								subjectName:null,
								recommendStatus:null,
								pageSize:5,
								pageNum:1
							}
						}]
					},{
						name:'订单管理',
						url:'/mall-admin',
						childModel:[{
							name:'订单管理',
							url:'/order',
							queryUrl:'/list',
							queryMethod:'GET',
							queryModel:{
								orderSn:null,
								receiverKeyword:null,
								status:null,
								orderType:null,
								sourceType:null,
								createTime:null,
								pageSize:5,
								pageNum:1
							}
						},{
							name:'订单退货管理',
							url:'/returnApply',
							queryUrl:'/list',
							queryMethod:'GET',
							deleteUrl:'/delete',
							deleteMethod:'POST',
							queryModel:{
								id:null,
								receiverKeyword:null,
								status:null,
								createTime:null,
								handleMan:null,
								handleTime:null
							}
						},{
							name:'退货原因',
							url:'/returnReason',
							insertUrl:'/create',
							insertMethod:'POST',
							deleteUrl:'/delete',
							deleteMethod:'POST',
							deleteUrlAppend:true,
							updateUrl:'/update',
							updateMethod:'POST',
							updateUrlAppend:true,
							queryUrl:'/list',
							queryMethod:'GET',
							queryModel:{
								pageSize:5,
								pageNum:1
							}
						},{
							name:'退货设置',
							url:'/orderSetting',
							insertUrl:'/create',
							insertMethod:'POST',
							deleteUrl:'/delete',
							deleteMethod:'POST',
							deleteUrlAppend:true,
							updateUrl:'/update',
							updateMethod:'POST',
							updateUrlAppend:true,
							queryUrl:'',
							queryMethod:'GET',
							queryUrlAppend:'id',
							queryModel:{
								id:null
							}
						},{
							name:'收货地址',
							url:'/companyAddress',
							insertUrl:'/create',
							insertMethod:'POST',
							deleteUrl:'/delete',
							deleteMethod:'POST',
							deleteUrlAppend:true,
							updateUrl:'/update',
							updateMethod:'POST',
							updateUrlAppend:true,
							queryUrl:'list',
							queryMethod:'GET'
						}]
					}],
				}
			}
		}
	}
</script>